baseURL = 'https://alfredwebdesign.com'
languageCode = 'en-us'
title = 'Alfred Web Design'
theme = 'client-theme'

[params]
  description = 'Professional web design services with modern static site solutions'
  decapCMS = true

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
  
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 20
  
  [[menu.main]]
    name = 'Services'
    url = '/services/'
    weight = 30
  
  [[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
